---

- name: All Tasks
  hosts: all
  gather_facts: yes
  become: yes

  tasks:
    - include: tasks/swapfile.install.yml

    - include: tasks/packages.upgrade.yml
      tags: upgrade
    - include: tasks/packages.install.yml

    - include: tasks/mariadb.install.yml
      tags:
        - db
        - mariadb
    - include: tasks/redis.install.yml
      tags: redis

    - include: tasks/python.install.yml
      tags: python
    - include: tasks/php.install.yml
      tags: php

    - include: tasks/nextcloud.install.yml
      tags: nextcloud

  handlers:
    - include: handlers/main.yml
