---
- import_playbook: ping.yml
- name: All Tasks
  hosts: all
  gather_facts: yes
  vars_files:
    - files/vars.yml
    - files/secrets/secrets.yml
  vars:
    - ansible_become_pass: "{{ sudo_password }}"

  tasks:
    - name: Gather OS-specific variables
      include_vars: "{{ item }}"
      with_first_found:
        - files/{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml
        - files/{{ ansible_distribution }}.yml
      tags: vars

    - import_tasks: tasks/swapfile.install.yml

    - import_tasks: tasks/packages.install.yml
      tags: packages
    - import_tasks: tasks/packages.upgrade.yml
      tags:
        - upgrade
        - packages

    - import_tasks: tasks/firewall.rules.yml
      tags: firewall

    - import_tasks: tasks/nginx.install.yml
      tags: nginx

    - import_tasks: tasks/php.install.yml
      tags: php

    - import_tasks: tasks/mariadb.install.yml
      tags:
        - db
        - mariadb
    - import_tasks: tasks/redis.install.yml
      tags: redis

    - import_tasks: tasks/nextcloud.install.yml
      tags: nextcloud
    
    - import_tasks: tasks/packages.upgrade.yml
      tags:
        - upgrade
        - packages

  handlers:
    - import_tasks: handlers/main.yml
