---
- name: Load vars
  hosts: all
  gather_facts: no
  tasks:
    - import_tasks: tasks/import_user_vars.yml

- import_playbook: ping.yml

- name: All Tasks
  hosts: all
  gather_facts: yes
  vars_files:
    - files/vars.yml
    - files/secrets/secrets.yml
  vars:
    - ansible_become_pass: "{{ sudo_password }}"

  tasks:
    - import_tasks: tasks/import_os_vars.yml

    - import_tasks: tasks/swapfile.install.yml

    - import_tasks: tasks/packages.install.yml
      tags: packages
    
    - import_tasks: tasks/firewall.rules.yml
      tags: firewall

    - import_tasks: tasks/packages.upgrade.yml
      tags:
        - upgrade
        - packages

    - import_tasks: tasks/nginx.install.yml
      tags: nginx

    - import_tasks: tasks/php.install.yml
      tags: php

    - import_tasks: tasks/mariadb.install.yml
      tags:
        - db
        - mariadb
    - import_tasks: tasks/redis.install.yml
      tags: redis

    - import_tasks: tasks/nextcloud.install.yml
      tags: nextcloud

  handlers:
    - import_tasks: handlers/main.yml
