---

- name: All Tasks
  hosts: all
  gather_facts: yes
  vars_files:
    - files/secrets/secrets.yml
  vars:
    - ansible_become_pass: "{{ sudo_password }}"
  tasks:
    - name: Upgrade Nextcloud
      become_user: nginx
      shell: php occ upgrade --no-interaction
      args:
        chdir: /usr/share/nginx/html/nextcloud
