---

- name: Add SSH keys
  hosts: all
  gather_facts: yes
  vars_files:
    - files/secrets/secrets.yml
  vars:
    - ansible_become_pass: "{{ sudo_password }}"
  tasks:
    - name: Gather OS-specific variables
      include_vars: "{{ item }}"
      with_first_found:
        - files/{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml
        - files/{{ ansible_distribution }}.yml
      tags: vars

    - name: SSH | Ensure sudo group exists
      become: yes
      group:
        name: sudo
        state: present
    
    - name: SSH | Ensure user exists
      become: yes
      user:
        name: "{{ ansible_ssh_user }}"
        group: sudo
        generate_ssh_key: yes
        shell: "/bin/bash"
        state: present

    - name: SSH | Ensure ~/.ssh directory exists
      become: yes
      file:
        path: /home/{{ ansible_ssh_user }}/.ssh
        state: directory
        owner: "{{ ansible_ssh_user }}"
        mode: 0700

    - name: SSH | Allow Access
      become: yes
      authorized_key:
        user: "{{ ansible_ssh_user }}"
        state: present
        key: "{{ lookup('file', public_key_file) }}"

    - name: SSH | Remove require tty
      become: yes
      lineinfile:
        regexp: "requiretty"
        dest: "{{ item }}"
        state: absent
      with_items:
        - /etc/sudoers
        - /etc/sudoers.d/os_defaults
  
    - name: SSH | Disable password-based authentication
      become: yes
      lineinfile:
        line: "{{ item.line }}"
        dest: /etc/ssh/sshd_config
        state: "{{ item.state }}"
      with_items:
        - { line: "PasswordAuthentication no", state: "present" }
        - { line: "PasswordAuthentication yes", state: "absent" }
        - { line: "PubkeyAuthentication yes", state: "present" }
        - { line: "ChallengeResponseAuthentication no", state: "present" }
      notify: SSH Reload
  
  handlers:
    - name: SSH Reload
      become: yes
      systemd:
        name: sshd
        state: reloaded
