---

- name: Add SSH keys
  hosts: all
  gather_facts: no
  tasks:
    - name: SSH | Get Name of Current User
      connection: local
      shell: whoami
      register: local_user
      changed_when: false

    - name: SSH | Allow Access
      become: yes
      authorized_key:
        user: "{{ local_user.stdout }}"
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"