---

- name: Firewall | Enable HTTP
  become: yes
  firewalld:
    service: http
    permanent: true
    zone: public
    state: enabled
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"
  register: http

- name: Firewall | Enable HTTPS
  become: yes
  firewalld:
    service: https
    permanent: true
    zone: public
    state: enabled
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"
  register: https

- name: Firewall | Ensure service is enabled
  become: yes
  systemd:
    name: firewalld
    enabled: yes
    state: started
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"

- name: Firewall | Reload service
  become: yes
  systemd:
    name: firewalld
    state: restarted
  when: (http|changed or https|changed) and (ansible_distribution == "CentOS" or ansible_distribution == "RedHat")
