---

- name: Firewall | Enable HTTP
  become: yes
  firewalld:
    service: http
    permanent: true
    zone: public
    state: enabled
  when: ansible_distribution == "CentOS"
  notify: Firewalld Reload

- name: Firewall | Enable HTTPS
  become: yes
  firewalld:
    service: https
    permanent: true
    zone: public
    state: enabled
  when: ansible_distribution == "CentOS"
  notify: Firewalld Reload

- name: Firewall | Ensure service is enabled
  become: yes
  service:
    name: firewalld
    state: started
  when: ansible_distribution == "CentOS"
