---

- name: Gather OS-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files/{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml
    - files/{{ ansible_distribution }}.yml
  tags: vars

- name: Gather user-specific variables
  include_vars: "{{ item }}"
  with_items:
    - files/secrets/{{ ansible_user }}.yml
