---

- name: MariaDB | Install repo
  become: yes
  yum_repository:
    name: MariaDB
    description: MariaDB repository
    baseurl: http://yum.mariadb.org/10.2/centos7-amd64
    enabled: yes
    gpgcheck: no
    gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    mode: 0644
  when: ansible_distribution == "CentOS" or ansible_distribution == 'Red Hat Enterprise Linux'

- name: MariaDB | Install MariaDB
  become: yes
  yum:
    update_cache: yes
    name: "{{ item }}"
    state: latest
  with_items:
    - MariaDB-server
    - MariaDB-client
    - MySQL-python
  when: ansible_distribution == "CentOS" or ansible_distribution == 'Red Hat Enterprise Linux'
  notify: MariaDB Reload

- name: MariaDB | Start service
  become: yes
  service:
    name: mariadb
    enabled: yes
    state: started

- name: MariaDB | Create root user
  mysql_user:
    login_user: root
    login_password: "{{ db_root_pass }}"
    check_implicit_admin: yes
    name: root
    password: "{{ db_root_pass }}"
    priv: "*.*:ALL,GRANT"
    host: "{{ item }}"
    state: present
  with_items:
    - localhost
    - ::1
    - 127.0.0.1

- name: MariaDB | Create Nextcloud database
  mysql_db:
    login_user: root
    login_password: "{{ db_root_pass }}"
    name: "{{ db_name }}"
    state: present

- name: MariaDB | Create DB user
  mysql_user:
    login_user: root
    login_password: "{{ db_root_pass }}"
    name: "{{ db_user }}"
    password: "{{ db_user_pass }}"
    priv: "{{ db_name }}.*:ALL,GRANT"
    state: present

- name: MariaDB | Flush privileges
  command: mysql -uroot -p{{ db_root_pass }} -ne "FLUSH PRIVILEGES;"
  changed_when: false

- name: MariaDB | Remove anonymous users
  mysql_user:
    login_user: root
    login_password: "{{ db_root_pass }}"
    user: ""
    state: absent

- name: MariaDB | Disallow remote root login
  mysql_user:
    login_User: root
    login_password: "{{ db_root_pass }}"
    user: root
    host: "{{ item }}"
    state: absent
  with_items:
    - localhost
    - "127.0.0.1"
    - "::1"

- name: MariaDB | Remove test database
  mysql_db:
    login_user: root
    login_password: "{{ db_root_pass }}"
    name: test
    state: absent

- name: MariaDB | Flush privileges - second
  command: mysql -uroot -p{{ db_root_pass }} -ne "FLUSH PRIVILEGES;"
  changed_when: false
