---

# TODO: Install NextCloud

# https://help.nextcloud.com/t/linux-packages-status/10216

- name: NextCloud | SELinux Configuration
  become: yes
  command: {{ item }}
  with_items:
    - semanage fcontext -a -t httpd_sys_rw_content_t '/var/www/html/nextcloud/data(/.*)?'
    - semanage fcontext -a -t httpd_sys_rw_content_t '/var/www/html/nextcloud/config(/.*)?'
    - semanage fcontext -a -t httpd_sys_rw_content_t '/var/www/html/nextcloud/apps(/.*)?'
    - semanage fcontext -a -t httpd_sys_rw_content_t '/var/www/html/nextcloud/.htaccess'
    - semanage fcontext -a -t httpd_sys_rw_content_t '/var/www/html/nextcloud/.user.ini'
    - restorecon -Rv '/var/www/html/nextcloud/'
  changed_when: false

- name: NextCloud | Disallow write access
  become: yes
  command: setsebool -P  httpd_unified  off
  changed_when: false

- name: NextCloud | Allow network access
  become: yes
  command: setsebool -P httpd_can_network_connect on
  changed_when: false

- name: NextCloud | Allow sendmail access
  become: yes
  command: setsebool -P httpd_can_sendmail on
