---

- name: NextCloud | Determine if release already downloaded
  stat: path=/home/{{ ansible_ssh_user }}/nextcloud.latest-12.tar.bz2 checksum_algorithm=sha256 get_checksum=yes
  changed_when: false
  register: nc_release

- name: NextCloud | Download latest signature
  get_url:
    url: https://download.nextcloud.com/server/releases/latest-12.tar.bz2.sha256
    dest: /home/{{ ansible_ssh_user }}/nextcloud.latest-12.tar.bz2.sha256
    mode: 0644
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    force: yes
  changed_when: false

- name: NextCloud | Gather latest signature
  shell: cat /home/{{ ansible_ssh_user }}/nextcloud.latest-12.tar.bz2.sha256 | awk '{print $1}'
  when: nc_release.stat.exists == True
  register: nc_signature
  changed_when: false

- name: NextCloud | Compare file hashes
  shell: "[ '{{ nc_release.stat.checksum }}' == '{{ nc_signature.stdout }}' ]"
  register: nc_hash
  changed_when: false
  when: nc_release.stat.exists == True

- name: NextCloud | Download latest release
  get_url:
    url: https://download.nextcloud.com/server/releases/latest-12.tar.bz2
    dest: /home/{{ ansible_ssh_user }}/nextcloud.latest-12.tar.bz2
    mode: 0644
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    force: yes
  when: nc_release.stat.exists != True or nc_hash.rc != 0

- name: NextCloud | Untar release
  unarchive:
    remote_src: yes
    src: /home/{{ ansible_ssh_user }}/nextcloud.latest-12.tar.bz2
    dest: /usr/share/nginx/html/
    owner: nginx
    group: nginx
    mode: 0775
    creates: /usr/share/nginx/html/nextcloud

- name: NextCloud | Add 404 page
  copy: src=../files/nextcloud/404.html dest=/usr/share/nginx/html/nextcloud/404.html owner=nginx group=nginx mode=0644

- name: NextCloud | Add 50x page
  copy: src=../files/nextcloud/50x.html dest=/usr/share/nginx/html/nextcloud/50x.html owner=nginx group=nginx mode=0644

- name: NextCloud | Copy Config
  template: src=../files/nextcloud/config.php.j2 dest=/usr/share/nginx/html/nextcloud/config/config.php owner=nginx group=nginx mode=0640

- name: NextCloud | SELinux Configuration
  become: yes
  command: "{{ item }}"
  with_items:
    - semanage fcontext -a -t httpd_sys_rw_content_t '/usr/share/nginx/html/nextcloud/data(/.*)?'
    - semanage fcontext -a -t httpd_sys_rw_content_t '/usr/share/nginx/html/nextcloud/config(/.*)?'
    - semanage fcontext -a -t httpd_sys_rw_content_t '/usr/share/nginx/html/nextcloud/apps(/.*)?'
    - semanage fcontext -a -t httpd_sys_rw_content_t '/usr/share/nginx/html/nextcloud/assets(/.*)?'
    - semanage fcontext -a -t httpd_sys_rw_content_t '/usr/share/nginx/html/nextcloud/.htaccess'
    - semanage fcontext -a -t httpd_sys_rw_content_t '/usr/share/nginx/html/nextcloud/.user.ini'
    - restorecon -Rv '/usr/share/nginx/html/nextcloud/'
  when: ansible_distribution == "CentOS"
  changed_when: false

- name: NextCloud | Disallow write access
  become: yes
  command: setsebool -P  httpd_unified  off
  when: ansible_distribution == "CentOS"
  changed_when: false

- name: NextCloud | Allow network access
  become: yes
  command: setsebool -P httpd_can_network_connect on
  when: ansible_distribution == "CentOS"
  changed_when: false

- name: NextCloud | Allow sendmail access
  become: yes
  when: ansible_distribution == "CentOS"
  command: setsebool -P httpd_can_sendmail on
  changed_when: false
