---

- name: NextCloud | Determine if release already downloaded
  stat: path=/home/{{ ansible_ssh_user }}/nextcloud.latest-12.tar.bz2 checksum_algorithm=sha256 get_checksum=yes
  changed_when: false
  register: nc_release

- name: NextCloud | Download latest signature
  get_url:
    url: https://download.nextcloud.com/server/releases/latest.tar.bz2.sha256
    dest: /home/{{ ansible_ssh_user }}/nextcloud.latest.tar.bz2.sha256
    mode: 0644
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    force: yes
  changed_when: false

- name: NextCloud | Gather local signature
  shell: cat /home/{{ ansible_ssh_user }}/nextcloud.latest.tar.bz2.sha256 | awk '{print $1}'
  when: nc_release.stat.exists == True
  register: nc_signature
  changed_when: false

- name: NextCloud | Compare signatures
  shell: "[ '{{ nc_release.stat.checksum }}' == '{{ nc_signature.stdout }}' ]"
  register: nc_hash
  changed_when: false
  when: nc_release.stat.exists == True

- name: NextCloud | Download latest release
  get_url:
    url: https://download.nextcloud.com/server/releases/latest.tar.bz2
    dest: /home/{{ ansible_ssh_user }}/nextcloud.latest.tar.bz2
    mode: 0644
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    force: yes
  when: nc_release.stat.exists != True or nc_hash.rc != 0

- name: NextCloud | Untar release
  unarchive:
    remote_src: yes
    src: /home/{{ ansible_ssh_user }}/nextcloud.latest.tar.bz2
    dest: /usr/share/nginx/html/
    owner: nginx
    group: nginx
    mode: 0775
    creates: /usr/share/nginx/html/nextcloud

- name: NextCloud | Add 404 page
  copy: src=../files/nextcloud/404.html dest=/usr/share/nginx/html/nextcloud/404.html owner=nginx group=nginx mode=0644

- name: NextCloud | Add 50x page
  copy: src=../files/nextcloud/50x.html dest=/usr/share/nginx/html/nextcloud/50x.html owner=nginx group=nginx mode=0644

- name: NextCloud | Install NextCloud
  become_user: nginx
  shell: php occ maintenance:install --database "mysql" --database-name "{{ db_name }}" --database-user "{{ db_user }}" --database-pass "{{ db_user_pass }}" --data-dir "{{ data_directory }}" --admin-user "{{ nextcloud_user }}" --admin-pass "{{ nextcloud_pass }}" && touch nextcloud.installed
  args:
    chdir: /usr/share/nginx/html/nextcloud
    creates: nextcloud.installed

- name: NextCloud | Determine latest version
  become_user: nginx
  shell: php occ -V
  args:
    chdir: /usr/share/nginx/html/nextcloud
  changed_when: false
  register: version

- name: NextCloud | Assign latest version
  set_fact:
    nextcloud_version: "{{ version.stdout }}"

- name: Upgrade NextCloud
  become_user: nginx
  shell: php occ upgrade --no-interaction && touch nextcloud.upgrade.installed
  args:
    chdir: /usr/share/nginx/html/nextcloud
    creates: nextcloud.upgrade.installed

- name: NextCloud | Copy config
  template: src=../files/nextcloud/config.php.j2 dest=/usr/share/nginx/html/nextcloud/config/config.php owner=nginx group=nginx mode=0640

- name: NextCLoud | SELinux configuration
  become: yes
  sefcontext:
    target: '{{ item }}'
    setype: httpd_sys_rw_content_t
    state: present
  with_items:
    - "{{ data_directory }}"
    - /usr/share/nginx/html/nextcloud/config(/.*)?
    - /usr/share/nginx/html/nextcloud/apps(/.*)?
    - /usr/share/nginx/html/nextcloud/assets(/.*)?
    - /usr/share/nginx/html/nextcloud/.htaccess
    - /usr/share/nginx/html/nextcloud/.user.ini
  when: ansible_distribution == "CentOS"

- name: NextCloud | Final SELinux configuration
  become: yes
  command: restorecon -Rv '/usr/share/nginx/html/nextcloud/'
  when: ansible_distribution == "CentOS"
  changed_when: false

- name: NextCloud | Disallow write access
  seboolean: name=httpd_unified persistent=yes state=off
  when: ansible_distribution == "CentOS"

- name: NextCloud | Allow network access
  seboolean: name=httpd_can_network_connect persistent=yes state=on
  when: ansible_distribution == "CentOS"

- name: NextCloud | Allow sendmail
  seboolean: name=httpd_can_sendmail persistent=yes state=on
  when: ansible_distribution == "CentOS"
