---

- name: Nginx | Install package
  become: yes
  yum:
    name: nginx
    state: latest
  when: ansible_distribution == "CentOS"

- name: Nginx | Add to Groups
  become: yes
  user:
    name: nginx
    group: nginx
    state: present

- name: Nginx | Ensure SSL directory
  become: yes
  file:
    path: /etc/nginx/ssl
    owner: root
    group: root
    state: directory

- name: Nginx | Check for local ECDH params
  become: no
  # Note that this relative path is from the project root, where `make run` should be called from.
  # local_action runs from the process CWD.
  local_action: stat path="files/secrets/nginx/ecdhparam.pem"
  register: ecdh_params

- name: Nginx | Ensure ECDH params
  become: yes
  copy:
    src: ../files/secrets/nginx/ecdhparam.pem
    dest: /etc/nginx/ssl/ecdhparam.pem
    owner: root
    group: root
    mode: 0644
  when: ecdh_params.stat.exists

- name: Nginx | Ensure FastCGI params
  become: yes
  copy:
    src: ../files/nginx/fastcgi_params
    dest: /etc/nginx/fastcgi_params
    owner: nginx
    group: nginx
    mode: 0644
  notify: Nginx Reload

- name: Nginx | Remove default site
  become: yes
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent
  notify: Nginx Reload

- name: Nginx | Remove the provided example_ssl.conf file
  become: yes
  file:
    path: /etc/nginx/conf.d/example_ssl.conf
    state: absent
  notify: Nginx Reload

- name: Nginx | Self-Signed - Generate certificate
  become: yes
  command: openssl req -x509 -new -nodes -days 3650 -keyout /etc/nginx/ssl/nextcloud-self.key -out /etc/nginx/ssl/nextcloud-self.crt -subj "/C={{ csr_country }}/ST={{ csr_state }}/L={{ csr_locality }}/O={{ csr_organization }}/OU={{ csr_organizational_unit }}/CN={{ server_domain }}/emailAddress={{ email }}"
  args:
    creates: /etc/nginx/ssl/nextcloud-self.crt
  notify: Nginx Reload

- name: Nginx | Stats on Certbot certificate
  become: yes
  stat:
    path: /etc/letsencrypt/live/{{ server_domain }}/fullchain.pem
  register: certbot_cert
  changed_when: false

- name: Nginx | Copy Nginx configuration
  become: yes
  template:
    src: ../files/nginx/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: nginx
    group: nginx
    mode: 0644
  notify: Nginx Reload

- name: Nginx | Start service
  become: yes
  service:
    name: nginx
    enabled: yes
    state: started

- name: Nginx | Install Certbot packages
  become: yes
  command: yum-config-manager --enable {{ item }}
  with_items:
    - rhui-REGION-rhel-server-extras 
    - rhui-REGION-rhel-server-optional
  when: ansible_distribution == "CentOS" and server_domain is defined
  changed_when: false

- name: Nginx | Install Certbot
  become: yes
  yum:
    name: certbot-nginx
    state: latest
  when: ansible_distribution == "CentOS" and server_domain is defined

- name: Nginx | Install certificate
  become: yes
  shell: certbot --staging --nginx certonly --email "{{ email }}" --agree-tos --domains "{{ server_domain }}" --non-interactive
  args:
    creates: /etc/letsencrypt/live/{{ server_domain }}/fullchain.pem
  notify: Nginx Reload

- name: Nginx | Reload stats on Certbot certificate
  become: yes
  stat:
    path: /etc/letsencrypt/live/{{ server_domain }}/fullchain.pem
  register: certbot_cert
  changed_when: false

- name: Nginx | Reload Nginx configuration
  become: yes
  template:
    src: ../files/nginx/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: nginx
    group: nginx
    mode: 0644
  notify: Nginx Reload

- name: Nginx | Ensure cron directory
  become: yes
  file:
    path: /opt/cron
    state: directory

- name: Nginx | Copy certificate renewal script
  become: yes
  copy:
    src: ../files/nginx/cert_renewal.sh
    dest: /opt/cron/cert_renewal.sh
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
  when: server_domain is defined and server_domain is defined

- name: Nginx | Schedule certificate renewal cron
  become: yes
  lineinfile:
    dest: /etc/cron.d/cert_renewal
    line: '43 8,20 * * * root bash /opt/cron/cert_renewal.sh'
    state: present
    create: yes
  when: server_domain is defined and server_domain is defined
