---

- name: Nginx | Install Package
  become: yes
  yum: name=nginx state=latest
  when: ansible_distribution == "CentOS"

- name: Nginx | Ensure SSL Directory
  file: path=/etc/nginx/ssl owner=root group=root state=directory

- name: Nginx | Ensure DH Params
  copy: src=files/secrets/nginx/dhparam.pem.encrypt dest=/etc/nginx/ssl/dhparam.pem owner=root group=root mode=0644

- name: Nginx | Remove Default Config
  file: path=/etc/nginx/conf.d/default.conf state=absent
  notify: Reload Nginx

- name: Nginx | Remove the provided example_ssl.conf file
  file: path=/etc/nginx/conf.d/example_ssl.conf state=absent
  notify: Reload Nginx

- name: Nginx | Start Service
  become: yes
  service: name=nginx enabled=yes state=started

- name: Nginx | Install Certbot Packages
  become: yes
  command: yum-config-manager --enable {{ item }}
  with_items:
    - rhui-REGION-rhel-server-extras 
    - rhui-REGION-rhel-server-optional
  when: ansible_distribution == "CentOS"

- name: Nginx | Install Certbot
  become: yes
  yum: name=certbot-nginx state=latest
  when: ansible_distribution == "CentOS"
  register: certbot

- name: Nginx | Install Certificate
  become: yes
  command: certbot --nginx
  when: certbot.changed
  notify: Nginx Reload

- name: Nginx | Copy Certificate Renewal Script
  copy: src=../files/nginx/cert_renewal.sh dest=/opt/cron/cert_renewal.sh owner={{ ansible_ssh_user }} group={{ ansible_ssh_user }} mode=0755

- name: Nginx | Schedule Certificate Renewal Cron
  become: yes
  lineinfile: dest=/etc/cron.d/cert_renewal line='43 8,20 * * * root bash /opt/cron/cert_renewal.sh' state=present create=yes
