---

- name: System | Upgrade Packages
  become: yes
  yum:
    update_cache: yes
    name: "*"
    exclude: "kernel*"
    state: latest
  when: ansible_distribution == "CentOS"

- name: System | Upgrade Kernel Packages
  become: yes
  yum:
    update_cache: yes
    name: "kernel*"
    state: latest
  when: ansible_distribution == "CentOS"
  register: kernel_upgraded

# Wait 1 minute to ensure the Ansible command has time to close.
- name: System | Reboot
  become: yes
  command: shutdown -r +1
  async: 0
  poll: 0
  ignore_errors: true
  when: kernel_upgraded.changed

- debug:
    msg: "Pausing to wait for remote machine reboot to begin."
  when: kernel_upgraded.changed

- pause:
    seconds: 70
  when: kernel_upgraded.changed

- name: System | Wait for reboot to complete
  become: no
  when: kernel_upgraded.changed
  local_action:
    module: wait_for
    host: "{{ ansible_host }}"
    port: 22
    timeout: 3600
    state: started