---

- name: Upgrade Packages
  become: yes
  yum: update_cache=yes name=* exclude=kernel* state=latest
  when: ansible_distribution == "CentOS"

- name: Upgrade Kernel Packages
  become: yes
  yum: update_cache=yes name=kernel* state=latest
  when: ansible_distribution == "CentOS"
  register: kernel_upgraded

- name: Reboot
  become: yes
  command: shutdown -r +1
  async: 0
  poll: 0
  ignore_errors: true
  when: kernel_upgraded.changed

- debug:
    msg: "Pausing to wait for reboot to begin."
  when: kernel_upgraded.changed

- pause:
    seconds: 65
  when: kernel_upgraded.changed

- name: Wait for reboot to complete
  become: no
  when: kernel_upgraded.changed
  local_action: wait_for host={{ ansible_ssh_host }} port=22 timeout=3600 state=started