---

- name: System | Upgrade Kernel Packages
  become: yes
  package:
    update_cache: yes
    name: "kernel*"
    state: latest
  register: kernel_upgraded

# Wait 1 minute to ensure the Ansible command has time to close.
- name: System | Reboot
  become: yes
  command: shutdown -r +1
  async: 0
  poll: 0
  ignore_errors: true
  when: kernel_upgraded is changed

- name: Pausing to wait for remote machine reboot to begin
  pause:
    seconds: 70
  when: kernel_upgraded is changed

- name: System | Wait for reboot to complete
  become: no
  when: kernel_upgraded is changed
  delegate_to: localhost
  wait_for:
    host: "{{ ansible_host }}"
    port: "{{ ssh_port | default('22')  }}"
    timeout: 300
    state: started

- name: Pausing as Vagrant needs more time
  pause:
    seconds: 60
  when: kernel_upgraded is changed and ansible_user == "vagrant"

- name: System | Upgrade Packages
  become: yes
  package:
    name: "*"
    state: latest
