---

- name: PHP | Install remi repository
  become: yes
  yum:
    name: http://rpms.remirepo.net/enterprise/remi-release-{{ ansible_distribution_major_version }}.rpm
    state: present

- name: PHP | Import remi GPG key
  become: yes
  rpm_key:
    key: http://rpms.remirepo.net/RPM-GPG-KEY-remi
    state: present

- name: PHP | Set PHP version
  become: yes
  command: yum-config-manager --enable remi-php{{ php_version }}
  changed_when: false

  # https://docs.nextcloud.com/server/13/admin_manual/installation/source_installation.html#prerequisites-for-manual-installation
- name: PHP | Install PHP
  become: yes
  yum:
    update_cache: yes
    name: "{{ item }}"
    state: latest
  with_items:
    - php-fpm
    - php-cli
    - php-opcache
    - php-ctype
    - php-dom
    - php-gd
    - php-iconv
    - php-json
    - php-libxml
    - php-mbstring
    - php-posix
    - php-simplexml
    - php-xmlreader
    - php-xmlwriter
    - php-zip
    - php-zlib
    - php-pdo_mysql
    - php-curl
    - php-fileinfo
    - php-bz2
    - php-intl
    - php-mcrypt
    - php-openssl
    - php-pcntl
    - php-redis
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"
  notify:
    - Nginx Reload
    - PHP Reload

- name: PHP | Copy www.conf
  become: yes
  copy:
    src: files/php/www.conf
    dest: /etc/php-fpm.d/www.conf
    owner: nginx
    group: nginx
    mode: 0644
  notify: PHP Reload

- name: PHP | Copy php.ini
  become: yes
  copy:
    src: files/php/php.ini
    dest: /etc/php.ini
    owner: nginx
    group: nginx
    mode: 0644
  notify: PHP Reload

- name: PHP | Create session directory
  become: yes
  file:
    path: /var/lib/php/session
    state: directory
    owner: nginx
    group: nginx

- name: PHP | Create cache directory
  become: yes
  file:
    path: /var/lib/php/opcache
    state: directory
    owner: nginx
    group: nginx

- name: PHP | Start PHP service
  become: yes
  systemd:
    name: php-fpm
    enabled: yes
    state: started
