---

- name: PHP | Install remi repository
  become: yes
  yum:
    name: http://rpms.remirepo.net/enterprise/remi-release-{{ ansible_distribution_major_version }}.rpm
    state: present
  when: ansible_distribution == "CentOS" or ansible_distribution == "Red Hat Enterprise Linux"
  register: remi_repo

- name: PHP | Import remi GPG key
  become: yes
  rpm_key:
    key: http://rpms.remirepo.net/RPM-GPG-KEY-remi
    state: present
  when: ansible_distribution == "CentOS" or ansible_distribution == "Red Hat Enterprise Linux"
  register: remi_key

- name: PHP | Update package cache
  become: yes
  yum:
    name: "*"
    update_cache: yes
  when: (remi_repo|changed or remi_key|changed) and (ansible_distribution == "CentOS" or ansible_distribution == "RedHat")

  # https://docs.nextcloud.com/server/13/admin_manual/installation/source_installation.html#prerequisites-for-manual-installation
- name: PHP | Install PHP
  become: yes
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ php_packages | replace('php', 'php' + php_version|string) }}"
  notify:
    - Nginx Reload
    - PHP Reload

- name: PHP | Copy www.conf
  become: yes
  copy:
    src: files/php/www.conf
    dest: "{{ php_www_conf_path }}"
    owner: nginx
    group: nginx
    mode: 0644
  notify: PHP Reload

- name: PHP | Copy php.ini
  become: yes
  copy:
    src: files/php/php.ini
    dest: "{{ php_ini_path }}"
    owner: nginx
    group: nginx
    mode: 0644
  notify: PHP Reload

- name: PHP | Create session directory
  become: yes
  file:
    path: /var/lib/php/session
    state: directory
    owner: nginx
    group: nginx

- name: PHP | Create cache directory
  become: yes
  file:
    path: /var/lib/php/opcache
    state: directory
    owner: nginx
    group: nginx

- name: PHP | Start PHP service
  become: yes
  systemd:
    name: "{{ php_service }}"
    enabled: yes
    state: started
