---

- name: PHP | Check if Remi Repository is installed
  become: yes
  command: rpm -q remi-release-7.3-2.el7.remi.noarch
  changed_when: false
  failed_when: false
  register: remi_installed

- name: PHP | Install Remi Repository
  become: yes
  command: rpm -Uvh http://rpms.remirepo.net/enterprise/remi-release-7.rpm
  when: remi_installed.stdout != "remi-release-7.3-2.el7.remi.noarch"
  register: php_remi

- name: PHP | Update Yum Cache
  become: yes
  yum: update_cache=yes name=* state=latest

- name: PHP | Set PHP version to 7.1
  become: yes
  command: yum-config-manager --enable remi-php71
  when: php_remi.changed

  # https://docs.nextcloud.com/server/12/admin_manual/installation/source_installation.html#prerequisites-for-manual-installation
- name: PHP | Install PHP
  become: yes
  yum: update_cache=yes name={{ item }} state=latest
  with_items:
    - php
    - php-opcache
    - php-ctype
    - php-dom
    - php-gd
    - php-iconv
    - php-json
    - php-libxml
    - php-mbstring
    - php-posix
    - php-simplexml
    - php-xmlreader
    - php-xmlwriter
    - php-zip
    - php-zlib
    - php-pdo_mysql
    - php-curl
    - php-fileinfo
    - php-bz2
    - php-intl
    - php-mcrypt
    - php-openssl
    - php-pcntl 
    - php-redis
  notify: HttpD Reload

- name: PHP | Apply Changes
  become: yes
  service: name=httpd state=restarted
  when: php_remi.changed