---

- name: Python | Install packages
  become: yes
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - python
    - python-pip
    - libselinux-python
    - libsemanage-python
  when: ansible_distribution == "CentOS" or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Python | Install pip packages
  become: yes
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - setuptools
    - wheel
    - virtualenv
