---

- name: Python | Install Packages
  become: yes
  yum: name={{ item }} state=latest
  with_items:
    - python
    - python-pip
    - python-setuptools
    - python-wheel
    - python-virtualenv
  when: ansible_distribution == "CentOS"