---

- name: Redis | Install Redis
  become: yes
  yum:
    name: redis
    state: latest
  when: ansible_distribution == "CentOS"

- name: Redis | Ensure socket directory
  become: yes
  file:
    path: "{{ redis_socket_dir }}"
    owner: redis
    group: root
    state: directory

- name: Redis | Copy configuration
  become: yes
  template:
    src: ../files/redis/redis.conf.j2
    dest: /etc/redis.conf
    owner: redis
    group: root
    mode: 0640
  notify: Redis Reload

- name: Redis | Add to Groups
  become: yes
  user:
    name: redis
    groups: redis,nginx
    state: present

- name: Redis | Set Linux kernel overcommit memory setting
  become: yes
  shell: sysctl vm.overcommit_memory=1 && touch redis-overcommit
  args:
    creates: redis-overcommit

- name: Redis | Persist overcommit memory setting
  become: yes
  lineinfile:
    dest: /etc/sysctl.conf
    line: "vm.overcommit_memory=1"
    state: present

- name: Redis | Set maximum backlog connections
  become: yes
  shell: sysctl -w net.core.somaxconn=512 && touch redis-backlog-connections
  args:
    creates: redis-backlog-connections

- name: Redis | Disable transparent huge pages
  become: yes
  shell: echo never > /sys/kernel/mm/transparent_hugepage/enabled && touch redis-transparent-pages
  args:
    creates: redis-transparent-pages

- name: Redis | Start Redis
  become: yes
  service:
    name: redis
    enabled: yes
    state: started
