---

- name: Redis | Install Redis
  become: yes
  package:
    name: "{{ redis_package }}"
    state: latest

- name: Redis | Copy configuration
  become: yes
  template:
    src: ../files/redis/redis.conf.j2
    dest: /etc/redis.conf
    owner: redis
    group: root
    mode: 0640
  notify: Redis Reload

- name: Redis | Increase TCP backlog setting
  become: yes
  sysctl:
    name: "{{ item }}"
    value: 1024
    state: present
    reload: yes
    sysctl_set: yes
  with_items:
    - net.core.somaxconn
    - net.ipv4.tcp_max_syn_backlog

- name: Redis | Enable overcommit memory
  become: yes
  sysctl:
    name: vm.overcommit_memory
    value: 1
    state: present
    sysctl_set: yes
    reload: yes

- name: Redis | Disable transparent huge pages
  become: yes
  shell: echo never > /sys/kernel/mm/transparent_hugepage/enabled && touch redis-transparent-pages
  args:
    creates: redis-transparent-pages

- name: Redis | Start Redis
  become: yes
  systemd:
    name: redis
    enabled: yes
    state: started
