---

- name: Create swapfile
  become: yes
  command: dd if=/dev/zero of=/swapfile bs=1024 count={{ swap_size }} creates=/swapfile

- name: Ensure swapfile permissions
  become: yes
  file:
    path: /swapfile
    owner: root
    group: root
    mode: 0600

- name: Format swapfile
  become: yes
  command: mkswap /swapfile
  args:
    creates: /swapfile-installed

- name: Activate swapfile
  become: yes
  shell: swapon /swapfile && touch /swapfile-installed
  args:
    creates: /swapfile-installed

- name: Persist swapfile
  become: yes
  lineinfile:
    dest: /etc/fstab
    line: "/swapfile swap swap defaults 0 0"
    state: present
