---

- name: Systemd Reload
  become: yes
  systemd:
    daemon-reload: yes

- name: MariaDB Reload
  become: yes
  systemd:
    name: mariadb
    state: restarted

- name: Redis Reload
  become: yes
  systemd:
    name: redis
    state: restarted

- name: Firewalld Reload
  become: yes
  systemd:
    name: firewalld
    state: restarted

- name: Nginx Reload
  become: yes
  systemd:
    name: nginx
    state: restarted

- name: PHP Reload
  become: yes
  systemd:
    name: php-fpm
    state: restarted
