---

- name: Systemd Reload
  command: systemctl daemon-reload

- name: MariaDB Reload
  service: name=mariadb state=restarted

- name: Redis Reload
  service: name=redis state=restarted

- name: Httpd Reload
  service: name=httpd state=restarted

- name: Firewalld Reload
  service: name=firewalld state=restarted

- name: Nginx Reload
  service: name=firewalld state=restarted